Repository neo4j/neo4j-browser, pull requests merged in 2019-09, with the labels that each got.

#962 :param v2
  e2e_tests/integration/0.index.spec.js
  e2e_tests/integration/multistatements.spec.js
  e2e_tests/integration/params.spec.js
  jest.config.js
  package.json
  src/browser/components/Directives.jsx
  src/browser/components/__snapshots__/Directives.test.js.snap
  src/browser/modules/Help/html/param.html
  src/browser/modules/Main/Main.jsx
  src/browser/modules/Stream/CypherFrame/ErrorsView.jsx
  src/browser/modules/Stream/CypherFrame/__snapshots__/AsciiView.test.js.snap
  src/browser/modules/Stream/CypherFrame/__snapshots__/CodeView.test.js.snap
  src/browser/modules/Stream/CypherFrame/__snapshots__/ErrorsView.test.js.snap
  src/browser/modules/Stream/CypherFrame/__snapshots__/PlanView.test.js.snap
  src/browser/modules/Stream/CypherFrame/__snapshots__/TableView.test.js.snap
  src/browser/modules/Stream/CypherFrame/__snapshots__/WarningsView.test.js.snap
  src/browser/modules/Stream/CypherFrame/index.jsx
  src/browser/modules/Stream/ErrorFrame.jsx
  src/browser/modules/Stream/ErrorFrame.test.js
  src/browser/modules/Stream/ParamsFrame.jsx
  src/browser/modules/Stream/__snapshots__/HistoryRow.test.js.snap
  src/browser/modules/Stream/__snapshots__/SchemaFrame.test.js.snap
  src/browser/modules/Stream/auto-exec-button.jsx
  src/browser/modules/Stream/auto-exec-button.test.jsx
  src/browser/modules/Stream/styled.jsx
  src/shared/modules/commands/helpers/lambdas.js
  src/shared/modules/commands/helpers/params.js
  src/shared/modules/commands/helpers/params.test.js
  src/shared/services/commandInterpreterHelper.js
  yarn.lock
Labels: enhancement, feature

#968 Bugfix saved favorites
  package.json
  src/browser/modules/Sidebar/favorites.utils.js
  src/shared/services/export-favorites/export-favorites.utils.js
  yarn.lock
Labels: DONT-MERGE, bug

#973 Prioritize bold_direct over bolt in discovery
  src/shared/modules/discovery/discoveryDuck.js
  src/shared/modules/discovery/discoveryDuck.test.js
Labels: canary, enhancement

#972 Default scheme `bolt://` -> `neo4j://` in canary
  src/browser/components/DesktopIntegration/helpers.js
  src/browser/modules/App/App.jsx
  src/browser/modules/Stream/Auth/ConnectionForm.test.js
  src/browser/modules/Stream/Queries/QueriesFrame.jsx
  src/browser/modules/Stream/Queries/QueriesFrame.test.js
  src/shared/modules/features/versionedFeatures.js
  src/shared/services/utils.js
  src/shared/services/utils.test.js
Labels: canary
