Repository neo4j/neo4j-browser, pull requests merged in 2019-08, with the labels that each got.

#950 Handle Infinity and -Infinity results correctly
  src/browser/modules/Stream/CypherFrame/AsciiView.jsx
  src/browser/modules/Stream/CypherFrame/TableView.jsx
  src/browser/modules/Stream/CypherFrame/helpers.js
  src/browser/modules/Stream/CypherFrame/helpers.test.js
  src/browser/modules/Stream/ParamsFrame.jsx
  src/shared/services/bolt/boltMappings.js
  src/shared/services/bolt/cypherTypesFormatting.js
  src/shared/services/bolt/cypherTypesFormatting.test.js
Labels: changelog

#952 Now displaying clickable urls in table and graph views
  package.json
  src/browser/components/clickable-urls.jsx
  src/browser/components/clickable-urls.test.js
  src/browser/modules/D3Visualization/components/Inspector.jsx
  src/browser/modules/Stream/CypherFrame/TableView.jsx
  src/browser/modules/Stream/CypherFrame/__snapshots__/TableView.test.js.snap
  yarn.lock
Labels: enhancement

#954 Export :history
  src/browser/modules/Stream/FrameTitlebar.jsx
  src/shared/utils/array-has-items.js
Labels: changelog, enhancement, feature

#958 Bugfix clickable urls
  src/browser/components/clickable-urls.jsx
  src/browser/modules/Stream/CypherFrame/TableView.jsx
Labels: bug

#955 Give user more connection feedback + add connection timeout configuration
  .eslintrc.json
  package.json
  src/browser/modules/App/App.jsx
  src/browser/modules/Main/Main.jsx
  src/browser/modules/Main/main.hooks.js
  src/browser/modules/Main/tests/slow-connection-connected.test.js
  src/browser/modules/Main/tests/slow-connection-disconnected.test.js
  src/browser/modules/Main/tests/slow-connection-long.test.js
  src/browser/modules/Main/tests/slow-connection-pending.test.js
  src/browser/modules/Main/tests/slow-connection-short.test.js
  src/browser/modules/Sidebar/Settings.jsx
  src/shared/modules/connections/connectionsDuck.js
  src/shared/modules/connections/connectionsDuck.test.js
  src/shared/modules/settings/__snapshots__/settingsDuck.test.js.snap
  src/shared/modules/settings/settingsDuck.js
  yarn.lock
Labels: changelog, enhancement, feature

#960 Remove temporary dev state in connections duck
  src/shared/modules/connections/connectionsDuck.js
Labels: bug

#957 Export query result records as JSON
  jest.config.js
  package.json
  src/browser/modules/Stream/CypherFrame/helpers.js
  src/browser/modules/Stream/CypherFrame/helpers.test.js
  src/browser/modules/Stream/FrameTitlebar.jsx
  src/browser/modules/Stream/styled.jsx
  yarn.lock
Labels: changelog, enhancement, feature
