Repository neo4j/neo4j-browser, pull requests merged in 2019-12, with the labels that each got.

#1006 Only show each database once in :dbs output
  src/browser/modules/Stream/Auth/DbsFrame.jsx
Labels: bug, changelog

#1007 Check if db exists before switching to it, throw if not
  e2e_tests/integration/multi-db.spec.js
  src/shared/services/commandInterpreterHelper.js
Labels: changelog

#1009 Update neo4j-driver to 4.0.0
  package.json
  yarn.lock
Labels: changelog

#1012 Prefer `bolt_routing` URL from discovery if it exists
  src/shared/modules/discovery/discoveryDuck.js
  src/shared/modules/discovery/discoveryDuck.test.js
Labels: changelog

#1008 Format node/relationship counts in sidebar, inspector and legend
  src/browser/modules/D3Visualization/components/Inspector.jsx
  src/browser/modules/D3Visualization/components/Legend.jsx
  src/browser/modules/DBMSInfo/MetaItems.jsx
  src/shared/utils/number-to-US-locale.js
  src/shared/utils/number-to-US-locale.test.js
Labels: changelog

#1013 Update SchemaFrame styling
  src/browser/modules/Docs/Docs.jsx
  src/browser/modules/Stream/HelpFrame.jsx
  src/browser/modules/Stream/SchemaFrame.jsx
  src/browser/modules/Stream/SchemaFrame.test.js
  src/browser/modules/Stream/__snapshots__/SchemaFrame.test.js.snap
  src/browser/modules/Stream/styled.jsx
  src/shared/modules/cypher/cypherDuck.js
Labels: changelog

#1017 User feedback running system commands
  e2e_tests/integration/multi-db.spec.js
  src/browser/modules/Stream/CypherFrame/helpers.js
Labels: changelog

#1010 Suggest strong passwords in change-password frame
  package.json
  src/browser/modules/Stream/Auth/ChangePasswordForm.jsx
  src/browser/modules/Stream/Auth/revealable-password-input.jsx
  src/browser/modules/Stream/Auth/styled.jsx
Labels: changelog, feature

#1020 Query plans view expanded by default
  e2e_tests/integration/plan.spec.js
  src/browser/modules/Stream/CypherFrame/PlanView.jsx
Labels: changelog
