Repository neo4j/neo4j-browser, pull requests merged in 2019-11, with the labels that each got.

#984 Statusbar and Code ligature issues
  src/browser/modules/Carousel/style.less
  src/browser/modules/Editor/styled.jsx
  src/browser/modules/Frame/styled.jsx
  src/browser/modules/Stream/Auth/styled.jsx
  src/browser/modules/Stream/AutoRefresh/styled.jsx
  src/browser/modules/Stream/CypherFrame/__snapshots__/ErrorsView.test.js.snap
  src/browser/modules/Stream/CypherFrame/__snapshots__/WarningsView.test.js.snap
  src/browser/modules/Stream/Queries/styled.jsx
  src/browser/modules/Stream/__snapshots__/SchemaFrame.test.js.snap
  src/browser/modules/Stream/styled.jsx
  src/browser/styles/global-styles.js
Labels: changelog

#985 Don’t auto-connect without credentials
  src/browser/modules/Stream/Auth/ConnectForm.jsx
  src/browser/modules/Stream/Auth/ConnectionForm.jsx
  src/browser/modules/Stream/Auth/ConnectionFrame.jsx
  src/browser/modules/Stream/Auth/styled.jsx
  src/shared/modules/connections/connectionsDuck.js
  src/shared/modules/connections/connectionsDuck.test.js
  src/shared/services/bolt/boltConnection.js
  src/shared/services/bolt/boltHelpers.js
Labels: changelog

#986 Bring back JSON data export
  src/browser/modules/Frame/FrameTitlebar.jsx
  src/browser/modules/Stream/FrameTitlebar.jsx
Labels: changelog

#987 Fix issue with `:server user add`.
  src/browser/modules/User/UserAdd.jsx
  src/shared/modules/cypher/boltUserHelper.js
Labels: changelog

#975 Various small improvements to sysinfo
  src/browser/modules/Stream/AutoRefresh/styled.jsx
  src/browser/modules/Stream/SysInfoFrame/helpers.js
  src/browser/modules/Stream/SysInfoFrame/index.jsx
  src/browser/modules/Stream/SysInfoFrame/legacyHelpers.jsx
  src/browser/modules/Stream/SysInfoFrame/sysinfo-utils.js
Labels: canary, changelog, enhancement

#993 Enable database switching with `:use xx` in multi-statement command
  e2e_tests/integration/multistatements.spec.js
  e2e_tests/support/commands.js
  src/browser/modules/Sidebar/Sidebar.jsx
  src/browser/modules/Stream/CypherScriptFrame/Summary.jsx
  src/shared/modules/commands/commandsDuck.js
  src/shared/services/commandInterpreterHelper.js
Labels: changelog

#1000 Bump to neo4j-driver to version 4.0.0-rc1
  package.json
  yarn.lock
Labels: canary, changelog

#998 Handle initial db selection
  e2e_tests/integration/bolt.spec.js
  e2e_tests/integration/multi-db.spec.js
  e2e_tests/support/commands.js
  src/browser/modules/DBMSInfo/DBMSInfo.jsx
  src/browser/modules/DBMSInfo/DatabaseSelector.jsx
  src/browser/modules/DBMSInfo/DatabaseSelector.test.jsx
  src/browser/modules/Main/styled.jsx
  src/browser/modules/Stream/Auth/DbsFrame.jsx
  src/browser/modules/Stream/CypherFrame/ErrorsView.jsx
  src/shared/modules/commands/commandsDuck.js
  src/shared/modules/commands/commandsDuck.test.js
  src/shared/modules/commands/useDb.test.js
  src/shared/modules/connections/connectionsDuck.js
  src/shared/modules/currentUser/currentUserDuck.js
  src/shared/modules/dbMeta/__snapshots__/dbMetaDuck.test.js.snap
  src/shared/modules/dbMeta/dbMetaDuck.js
  src/shared/modules/features/versionedFeatures.js
  src/shared/rootEpic.js
  src/shared/services/bolt/bolt.js
  src/shared/services/bolt/boltConnection.js
  src/shared/services/commandInterpreterHelper.js
  src/shared/services/cypherErrorsHelper.js
Labels: canary

#999 Fix errors in community edition
  src/browser/modules/DBMSInfo/UserDetails.jsx
  src/browser/modules/User/UserAdd.jsx
  src/browser/modules/User/UserList.jsx
  src/shared/modules/dbMeta/dbMeta.utils.js
Labels: canary

#997 use new output of show databases
  src/browser/modules/DBMSInfo/DatabaseSelector.jsx
  src/browser/modules/Stream/SysInfoFrame/helpers.js
  src/shared/modules/dbMeta/dbMetaDuck.js
Labels: canary
