Repository neo4j/neo4j-browser, pull requests merged in 2020-01, with the labels that each got.

#1035 Deeplink to slide in remote guides
  src/browser/modules/Carousel/Carousel.jsx
  src/browser/modules/Docs/Docs.jsx
  src/browser/modules/Stream/PlayFrame.jsx
  src/shared/modules/commands/commandsDuck.js
  src/shared/services/commandInterpreterHelper.js
  src/shared/services/commandUtils.js
  src/shared/services/commandUtils.test.js
Labels: enhancement, feature

#956 Add URL param support for populating editor with Cypher and parameters
  src/shared/modules/editor/editorDuck.js
  src/shared/modules/editor/editorDuck.test.js
Labels: changelog

#1040 Bugfix browser implicit lambda with newlines
  e2e_tests/integration/multistatements.spec.js
  package.json
  yarn.lock
Labels: bug, changelog

#1042 Allow database names to be escaped with back ticks with the `:use` command
  e2e_tests/integration/multi-db.spec.js
  src/browser/modules/DBMSInfo/DatabaseSelector.jsx
  src/browser/modules/DBMSInfo/DatabaseSelector.test.jsx
  src/browser/modules/DBMSInfo/MetaItems.jsx
  src/browser/modules/Stream/Auth/DbsFrame.jsx
  src/shared/services/commandInterpreterHelper.js
  src/shared/services/utils.js
  src/shared/services/utils.test.js
Labels: changelog

#1048 Use best practices driver transaction functions by default
  e2e_tests/integration/loadcsv.spec.js
  src/shared/modules/commands/commandsDuck.js
  src/shared/modules/commands/cypher.test.js
  src/shared/modules/commands/helpers/cypher.js
  src/shared/modules/cypher/cypherDuck.js
  src/shared/services/bolt/bolt.js
  src/shared/services/bolt/boltConnection.js
  src/shared/services/bolt/boltHelpers.js
  src/shared/services/bolt/boltHelpers.test.js
  src/shared/services/bolt/boltWorker.js
  src/shared/services/commandInterpreterHelper.js
Labels: changelog

#1054 Fix HTML rendering issues on query results
  package.json
  src/browser/components/clickable-urls.jsx
  src/browser/components/clickable-urls.test.js
  src/browser/modules/Stream/CypherFrame/TableView.jsx
  src/browser/modules/Stream/CypherFrame/TableView.test.js
  src/browser/modules/Stream/CypherFrame/VisualizationView.test.js
  src/browser/modules/Stream/CypherFrame/__snapshots__/TableView.test.js.snap
  src/browser/modules/Stream/CypherFrame/__snapshots__/VisualizationView.test.js.snap
  src/shared/services/santize.utils.js
  yarn.lock
Labels: changelog

#1057 Add `:help auto` + link to it from relevant errors and docs
  src/browser/documentation/dynamic/cypher.jsx
  src/browser/documentation/help/auto.jsx
  src/browser/documentation/help/load-csv.jsx
  src/browser/documentation/index.js
  src/browser/modules/Stream/CypherFrame/ErrorsView.jsx
  src/browser/modules/Stream/CypherFrame/ErrorsView.test.js
  src/shared/services/cypherErrorsHelper.js
Labels: changelog
