Repository neo4j/neo4j-browser, pull requests merged in 2020-05, with the labels that each got.

#1089 Enable multi statement mode in editor by default
  src/shared/modules/settings/__snapshots__/settingsDuck.test.js.snap
  src/shared/modules/settings/settingsDuck.js
Labels: changelog

#1092 Use new plan field ‘Details’ to plan visualization
  src/browser/modules/D3Visualization/lib/visualization/components/queryPlan.js
Labels: changelog

#1094 Fix so browser doesn't execute meta query on system db
  src/shared/modules/dbMeta/dbMetaDuck.js
Labels: changelog

#1096 More reliable connection status check
  e2e_tests/integration/commands.spec.js
  e2e_tests/integration/debug-command.spec.js
  src/browser/modules/Stream/Auth/ConnectionForm.jsx
  src/browser/modules/Stream/Auth/ConnectionForm.test.js
  src/browser/modules/Stream/Auth/ServerStatusFrame.jsx
  src/browser/modules/Stream/Auth/ServerStatusFrame.test.js
  src/shared/modules/dbMeta/__snapshots__/dbMetaDuck.test.js.snap
  src/shared/modules/dbMeta/dbMetaDuck.js
  src/shared/modules/features/featuresDuck.js
  src/shared/modules/features/featuresDuck.test.js
  src/shared/services/commandInterpreterHelper.js
Labels: changelog

#1093 Use public procedure to read server conf, if it exists
  e2e_tests/integration/debug-command.spec.js
  src/shared/modules/dbMeta/dbMetaDuck.js
  src/shared/modules/features/featuresDuck.js
  src/shared/rootEpic.js
Labels: DONT-MERGE

#1101 Add sidebar links to browser release, changelog, and developer pages
  src/browser/modules/Sidebar/About.jsx
  src/browser/modules/Sidebar/Documents.jsx
Labels: changelog

#1102 Fix reading `username` from connectURL param
  src/shared/modules/connections/connectionsDuck.js
  src/shared/modules/connections/connectionsDuck.test.js
  src/shared/modules/discovery/discoveryDuck.js
Labels: changelog

#1104 Add re-run button to all frame types
  src/browser/modules/Frame/FrameTitlebar.jsx
  src/browser/modules/Stream/Queries/QueriesFrame.jsx
  src/browser/modules/Stream/SysInfoFrame/index.jsx
  src/browser/modules/Stream/auto-exec-button.test.jsx
  src/browser/modules/User/UserList.jsx
  src/shared/modules/commands/commandsDuck.js
  src/shared/modules/stream/streamDuck.js
Labels: changelog

#1103 Fix auth scheme error from driver when auth is disabled + reflect auth status on `:server connect` frame`
  src/browser/modules/Stream/Auth/ConnectionForm.jsx
  src/browser/modules/Stream/Auth/ConnectionForm.test.js
  src/shared/modules/connections/connectionsDuck.js
  src/shared/services/bolt/bolt.js
  src/shared/services/bolt/globalDrivers.js
Labels: changelog

#1106 Fix sending tx metadata with each query
  e2e_tests/integration/bolt.spec.js
  src/shared/services/bolt/transactions.js
Labels: changelog

#1107 Fix only executing relevant background queries (auth, cluster)
  src/shared/modules/connections/connectionsDuck.js
  src/shared/modules/currentUser/currentUserDuck.js
  src/shared/modules/dbMeta/dbMetaDuck.js
Labels: changelog

#1090 Feature relatable
  package.json
  src/browser/modules/D3Visualization/components/Explorer.jsx
  src/browser/modules/D3Visualization/components/Inspector.jsx
  src/browser/modules/Stream/CypherFrame/AsciiView.jsx
  src/browser/modules/Stream/CypherFrame/AsciiView.test.js
  src/browser/modules/Stream/CypherFrame/CodeView.jsx
  src/browser/modules/Stream/CypherFrame/CodeView.test.js
  src/browser/modules/Stream/CypherFrame/TableView.jsx
  src/browser/modules/Stream/CypherFrame/VisualizationView.jsx
  src/browser/modules/Stream/CypherFrame/__snapshots__/AsciiView.test.js.snap
  src/browser/modules/Stream/CypherFrame/__snapshots__/CodeView.test.js.snap
  src/browser/modules/Stream/CypherFrame/__snapshots__/TableView.test.js.snap
  src/browser/modules/Stream/CypherFrame/__snapshots__/relatable-view.test.js.snap
  src/browser/modules/Stream/CypherFrame/helpers.js
  src/browser/modules/Stream/CypherFrame/index.jsx
  src/browser/modules/Stream/CypherFrame/index.test.js
  src/browser/modules/Stream/CypherFrame/relatable-view.jsx
  src/browser/modules/Stream/CypherFrame/relatable-view.styled.js
  src/browser/modules/Stream/CypherFrame/relatable-view.test.js
  src/browser/modules/Stream/__snapshots__/HistoryRow.test.js.snap
  src/browser/modules/Stream/styled.jsx
  src/shared/modules/settings/__snapshots__/settingsDuck.test.js.snap
  src/shared/modules/settings/settingsDuck.js
  src/shared/services/bolt/bolt.js
  src/shared/services/bolt/boltMappings.js
  src/shared/services/bolt/boltMappings.test.js
  yarn.lock
Labels: bug, enhancement
