Repository neo4j/neo4j-browser, pull requests merged in 2021-11, with the labels that each got.

#1582 Neo4j 4.4 config_clients.allow_telemetry
  docs/modules/ROOT/pages/operations/product-analytics.adoc
Labels: documentation, 4.4

#1590 update SSO content
  docs/modules/ROOT/pages/operations/browser-sso.adoc
Labels: Work in progress, documentation

#1611 Improves the Browser settings information
  docs/modules/ROOT/images/adjust-settings.png
  docs/modules/ROOT/pages/operations/browser-settings.adoc
  docs/modules/ROOT/pages/visual-tour.adoc
Labels: browser manual, documentation

#1614 updated centrally hosted browser
  docs/modules/ROOT/pages/deployment-modes/neo4j-server.adoc
  docs/modules/ROOT/pages/deployment-modes/web-application.adoc
Labels: documentation

#1616 Docs graph relayout
  docs/modules/ROOT/images/dismiss-node.png
  docs/modules/ROOT/images/expand-collapse.png
  docs/modules/ROOT/images/unlock-relayout.png
  docs/modules/ROOT/pages/operations/result-frames.adoc
Labels: browser manual
